import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Html, Line, OrbitControls, Sparkles, Stars } from '@react-three/drei';
import * as THREE from 'three';
import { Activity, BookOpen, ChevronRight, CircleHelp, Command, Copy, FolderKanban, Grid2X2, Menu, PanelRight, Search, Settings, SlidersHorizontal, Sparkles as SparkIcon, X } from 'lucide-react';
import './styles.css';

type Category = 'Profile'|'Projects'|'Journal'|'System'|'Knowledge'|'Uncategorized';
type Relation = 'direct'|'category'|'mention';
type NodeData = {id:string; title:string; category:Category; description:string; path:string; tags:string[]; connections:number; hub?:boolean; position:[number,number,number]};
type EdgeData = {source:string; target:string; relation:Relation};
const COLORS:Record<Category,string>={Profile:'#38bdf8',Projects:'#a78bfa',Journal:'#34d399',System:'#fbbf24',Knowledge:'#f87171',Uncategorized:'#64748b'};
const REL_COLORS:Record<Relation,string>={direct:'#bff3ff',category:'#ffd27a',mention:'#b7a6ff'};
const relationName:Record<Relation,string>={direct:'Direct connection',category:'Shared category',mention:'Mention / semantic'};
const raw=[
 ['Profile','Profile','The operator and the preferences that shape this workspace.','memory/profile.md',['operator','preferences'],['Responsive Design','Mayster Heating & Air']],
 ['Responsive Design','Profile','Practical fit and legibility matter more than simply increasing size.','memory/preferences.md',['preferences','ui'],['Personal HQ','Profile']],
 ['Mayster Heating & Air','Projects','Review Starboard operations and internal incentive tracking.','projects/mayster-starboard.md',['mayster','operations'],['Personal HQ','Profile']],
 ['Personal HQ','Projects','The agent workspace: a calm interface for intent, memory, and momentum.','projects/personal-hq.md',['hq','interface'],['ARIA','Responsive Design','Graph UI']],
 ['Graph UI','Projects','A graph-first exploration surface for navigating connected context.','projects/graph-ui.md',['design','visualization'],['Personal HQ','Three.js']],
 ['ARIA','System','Autonomous Reasoning & Intelligence Agent. Tool-backed, direct, and honest about uncertainty.','system/aria.md',['agent','identity'],['Hermes','Personal HQ']],
 ['Hermes','System','The operating layer that turns intent into verified action.','system/hermes.md',['agent','tools'],['ARIA','Obsidian']],
 ['Obsidian','Knowledge','Markdown vault substrate with wikilinks, tags, and frontmatter.','knowledge/obsidian.md',['notes','knowledge'],['Graph UI','Personal HQ']],
 ['Three.js','Knowledge','WebGL rendering engine used for the spatial graph surface.','knowledge/threejs.md',['webgl','rendering'],['Graph UI','React']],
 ['React','Knowledge','Component model for the application shell and interaction state.','knowledge/react.md',['frontend','components'],['Graph UI','TypeScript']],
 ['TypeScript','Knowledge','Typed language layer that keeps the graph data model explicit.','knowledge/typescript.md',['code','frontend'],['React']],
 ['Open questions','Journal','What should write-back conflict resolution feel like in the real vault?','journal/open-questions.md',['journal','exploration'],['Obsidian','Personal HQ']],
];
const stable=(s:string)=>{let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0)/4294967296};
function buildGraph(){const hubs=raw.filter(r=>r[0]===r[1]).map(r=>r[0] as string);const nodes:NodeData[]=[];const byHub=new Map<string,NodeData>();const golden=Math.PI*(3-Math.sqrt(5));hubs.forEach((title,i)=>{const y=1-(i/(Math.max(hubs.length-1,1)))*2;const radius=Math.sqrt(1-y*y);const a=golden*i;const p:[number,number,number]=[Math.cos(a)*radius*18,y*18,Math.sin(a)*radius*18];const n={id:title,title,category:title as Category,description:raw.find(r=>r[0]===title)?.[2] as string,path:raw.find(r=>r[0]===title)?.[3] as string,tags:raw.find(r=>r[0]===title)?.[4] as string[],connections:0,hub:true,position:p};nodes.push(n);byHub.set(title,n)});raw.filter(r=>r[0]!==r[1]).forEach((r,i)=>{const hub=byHub.get(r[1] as string)||byHub.get('Uncategorized')||nodes[0];const a=golden*(i+1)+stable(r[0] as string)*.9;const y=(stable((r[0] as string)+'y')-.5)*2;const radius=6.3+(stable((r[0] as string)+'r')*3.3);const p:[number,number,number]=[hub.position[0]+Math.cos(a)*radius+(stable(r[0] as string)*3.2-1.6),hub.position[1]+y*radius*.55+(stable((r[0] as string)+'z')*3.2-1.6),hub.position[2]+Math.sin(a)*radius];nodes.push({id:r[0] as string,title:r[0] as string,category:r[1] as Category,description:r[2] as string,path:r[3] as string,tags:r[4] as string[],connections:0,position:p})});const edges:EdgeData[]=[];raw.forEach(r=>{const source=r[0] as string;(r[5] as string[]).forEach((target,j)=>{if(nodes.some(n=>n.id===target)&&!edges.some(e=>(e.source===source&&e.target===target)||(e.source===target&&e.target===source)))edges.push({source,target,relation:j===0?'direct':'mention'})})});for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)if(nodes[i].category===nodes[j].category&&nodes[i].category!==nodes[j].category&&!edges.some(e=>(e.source===nodes[i].id&&e.target===nodes[j].id)||(e.source===nodes[j].id&&e.target===nodes[i].id)))edges.push({source:nodes[i].id,target:nodes[j].id,relation:'category'});nodes.forEach(n=>n.connections=edges.filter(e=>e.source===n.id||e.target===n.id).length);return {nodes,edges}};
const graph=buildGraph();
function NodeMesh({node,selected,hovered,onSelect,onHover,dim}:{node:NodeData;selected:boolean;hovered:boolean;dim:boolean;onSelect:()=>void;onHover:(v:boolean)=>void}){const ref=useRef<THREE.Group>(null);const color=COLORS[node.category];useFrame(({clock})=>{if(!ref.current)return;const t=clock.getElapsedTime();ref.current.position.y=node.position[1]+Math.sin(t*.6+stable(node.id)*8)*.26;const pulse=1+Math.sin(t*1.3+stable(node.id)*12)*.035;ref.current.scale.setScalar((selected?1.2:hovered?1.1:1)*pulse)});return <group ref={ref} position={node.position} onClick={e=>{e.stopPropagation();onSelect()}} onPointerOver={e=>{e.stopPropagation();onHover(true)}} onPointerOut={()=>onHover(false)}>
 <mesh><sphereGeometry args={[node.hub?1.65:0.72+Math.min(node.connections,5)*.08, node.hub?24:18, node.hub?16:12]}/><meshStandardMaterial color={color} emissive={color} emissiveIntensity={selected?1.8:hovered?1.15:.65} roughness={.35} transparent opacity={dim?.13:.9}/></mesh>
 <mesh scale={node.hub?2.6:1.9}><sphereGeometry args={[node.hub?1.65:0.72+Math.min(node.connections,5)*.08,12,8]}/><meshBasicMaterial color={color} transparent opacity={dim?.012:selected?.18:hovered?.16:.055} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh>
 {(hovered||selected||node.connections>=5)&&<Html center distanceFactor={node.hub?12:16} style={{pointerEvents:'none'}}><div className={'node-label '+(selected?'selected':'')} style={{'--node-color':color} as React.CSSProperties}><b>{node.title}</b><span>{node.category} · {node.connections}</span></div></Html>}
 </group>}
function EdgeLine({edge,active,dim}:{edge:EdgeData;active:boolean;dim:boolean}){const a=graph.nodes.find(n=>n.id===edge.source)!,b=graph.nodes.find(n=>n.id===edge.target)!;const points=[a.position,new THREE.Vector3((a.position[0]+b.position[0])/2,(a.position[1]+b.position[1])/2+Math.sin(stable(edge.source+edge.target)*8)*2.5,(a.position[2]+b.position[2])/2),b.position];return <><Line points={points} color={REL_COLORS[edge.relation]} transparent opacity={dim?.035:active?.85:.2} lineWidth={active?1.7:.7}/>{active&&<Pulse a={a.position} b={b.position} color={REL_COLORS[edge.relation]} speed={edge.relation==='direct'?.16:edge.relation==='category'?.09:.05}/>}</>}
function Pulse({a,b,color,speed}:{a:[number,number,number];b:[number,number,number];color:string;speed:number}){const ref=useRef<THREE.Mesh>(null);useFrame(({clock})=>{if(ref.current){const t=(clock.getElapsedTime()*speed+.31)%1;ref.current.position.lerpVectors(new THREE.Vector3(...a),new THREE.Vector3(...b),t)}});return <mesh ref={ref}><sphereGeometry args={[.22,10,8]}/><meshBasicMaterial color={color} transparent opacity={.95} blending={THREE.AdditiveBlending}/></mesh>}
function CameraRig({selected}:{selected:NodeData|null}){const {camera}=useThree();const controls=useRef<any>(null);useFrame(()=>{if(!controls.current)return;const target=selected?new THREE.Vector3(...selected.position):new THREE.Vector3(0,0,0);const desired=selected?target.clone().add(new THREE.Vector3(0,2,11)):new THREE.Vector3(0,14,56);camera.position.lerp(desired,.055);controls.current.target.lerp(target,.055)});return <OrbitControls ref={controls} enableDamping dampingFactor={.07} rotateSpeed={.72} zoomSpeed={1.15} minDistance={2.2} maxDistance={160} autoRotate={!selected} autoRotateSpeed={.35}/>}
function GraphScene({selected,setSelected,filter,query}:{selected:NodeData|null;setSelected:(n:NodeData|null)=>void;filter:Category|'All';query:string}){const [hover,setHover]=useState<string|null>(null);const visible=graph.nodes.filter(n=>(filter==='All'||n.category===filter)&&(!query||`${n.title} ${n.category} ${n.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())));const visibleIds=new Set(visible.map(n=>n.id));return <Canvas camera={{position:[0,14,56],fov:50,near:.1,far:240}} dpr={[1,1.7]} gl={{antialias:true,alpha:true}} onPointerMissed={()=>setSelected(null)}><fog attach="fog" args={['#070b14',80,240]}/><ambientLight intensity={.42} color="#1d2741"/><pointLight position={[32,30,18]} intensity={18} distance={110} color="#38bdf8"/><pointLight position={[-28,12,-24]} intensity={13} distance={100} color="#a78bfa"/><Stars radius={150} depth={75} count={window.innerWidth<700?650:1400} factor={1.2} saturation={.1} fade speed={.3}/><Sparkles count={window.innerWidth<700?80:180} scale={[100,65,100]} size={1.1} speed={.22} color="#8db8ff"/><gridHelper args={[180,36,'#17304a','#0a1424']} position={[0,-28,0]} rotation={[0,0,0]} material-transparent material-opacity={.12}/>{graph.edges.map((e,i)=><EdgeLine key={i} edge={e} active={!!selected&&(e.source===selected.id||e.target===selected.id)||hover!==null&&(e.source===hover||e.target===hover)} dim={!!selected&&!((e.source===selected.id||e.target===selected.id))}/>) }{graph.nodes.map(n=><NodeMesh key={n.id} node={n} selected={selected?.id===n.id} hovered={hover===n.id} dim={!!selected&&selected.id!==n.id&&!graph.edges.some(e=>(e.source===selected.id&&e.target===n.id)||(e.target===selected.id&&e.source===n.id))||!visibleIds.has(n.id)} onSelect={()=>setSelected(n)} onHover={v=>setHover(v?n.id:null)}/>)}<CameraRig selected={selected}/></Canvas>}
function Rail({view,setView}:{view:string;setView:(v:string)=>void}){const items=[['overview','Overview',Grid2X2],['graph','Graph',Command],['collections','Collections',FolderKanban],['activity','Activity',Activity],['settings','Settings',Settings]] as const;return <aside className="rail"><div className="rail-mark">A</div>{items.map(([id,label,Icon])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)} aria-label={label} title={label}><Icon size={18}/></button>)}<div className="rail-spacer"/><button aria-label="Toggle navigation"><PanelRight size={17}/></button></aside>}
function Header({query,setQuery,onMenu}:{query:string;setQuery:(s:string)=>void;onMenu:()=>void}){return <header className="header"><button className="mobile-menu" onClick={onMenu} aria-label="Open navigation"><Menu size={19}/></button><div className="title-lockup"><div className="orb"/><div><b>KNOWLEDGE GRAPH</b><span><i/> LIVE · ARIA SECOND BRAIN</span></div></div><div className="header-actions"><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search nodes, tags, paths…" aria-label="Search knowledge graph"/><kbd>⌘ K</kbd></label><button className="icon-btn" aria-label="Filter"><SlidersHorizontal size={17}/></button><button className="icon-btn" aria-label="Appearance"><SparkIcon size={17}/></button><div className="avatar">MF</div></div></header>}
function Detail({node,onClose,onAsk}:{node:NodeData;onClose:()=>void;onAsk:()=>void}){const related=graph.edges.filter(e=>e.source===node.id||e.target===node.id).map(e=>{const id=e.source===node.id?e.target:e.source;return {node:graph.nodes.find(n=>n.id===id)!,relation:e.relation}});return <aside className="detail-panel"><div className="detail-top"><div className="detail-kicker">NODE INSPECTOR</div><button className="icon-btn" onClick={onClose} aria-label="Close details"><X size={17}/></button></div><div className="detail-title"><span className="node-dot" style={{background:COLORS[node.category],boxShadow:`0 0 16px ${COLORS[node.category]}`}}/><div><h2>{node.title}</h2><span className="category" style={{color:COLORS[node.category]}}>{node.category.toUpperCase()}</span></div></div><div className="path"><BookOpen size={13}/>{node.path}<button aria-label="Copy identifier" onClick={()=>navigator.clipboard?.writeText(node.path)}><Copy size={12}/></button></div><p className="description">{node.description}</p><div className="meta-row"><span>UPDATED <b>today</b></span><span>LINKS <b>{node.connections}</b></span></div><div className="section-label">CONNECTED CONTEXT</div><div className="related">{related.length?related.map(x=><button key={x.node.id} onClick={()=>onAsk()}><span className="mini-dot" style={{background:COLORS[x.node.category]}}/><span>{x.node.title}</span><small>{relationName[x.relation]}</small><ChevronRight size={13}/></button>):<p className="muted">No connections yet.</p>}</div><div className="detail-actions"><button onClick={onAsk}><CircleHelp size={14}/>Ask ARIA</button><button onClick={()=>window.open('obsidian://open?vault=&file='+encodeURIComponent(node.path),'_blank')}><BookOpen size={14}/>Open note</button></div></aside>}
function Legend(){return <div className="legend"><div className="legend-head"><span>GRAPH SIGNAL</span><b>{graph.nodes.length} NODES · {graph.edges.length} EDGES</b></div><div className="legend-items">{(['direct','category','mention'] as Relation[]).map(r=><span key={r}><i style={{background:REL_COLORS[r],boxShadow:`0 0 7px ${REL_COLORS[r]}`}}/>{relationName[r]}</span>)}</div><div className="legend-foot"><span><i className="live-dot"/>DEMO DATA · READY</span><span>DRAG TO ORBIT · SCROLL TO ZOOM</span></div></div>}
function Chat({selected}:{selected:NodeData|null}){const [text,setText]=useState('');const [messages,setMessages]=useState(['The graph is quiet, but not asleep. Select a node and I’ll trace its reachable context.']);useEffect(()=>{const h=(e:Event)=>setText('Tell me everything you know about '+(e as CustomEvent<string>).detail);window.addEventListener('ask-node',h);return()=>window.removeEventListener('ask-node',h)},[]);const send=()=>{if(!text.trim())return;const q=text;setMessages(m=>[...m,q,'I’m traversing the visible neighborhood now. I’ll keep the answer grounded in connected notes and mark uncertainty where the graph is thin.']);setText('')};return <div className="chat"><div className="chat-head"><span><SparkIcon size={13}/> COMMS TERMINAL</span><small>{selected?`FOCUS · ${selected.title}`:'READY'}</small></div><div className="messages">{messages.map((m,i)=><div key={i} className={i%3===1?'user-msg':'agent-msg'}>{m}</div>)}</div><div className="chat-input"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Talk to ARIA…"/><button onClick={send} aria-label="Send message"><ChevronRight size={16}/></button></div></div>}
function App(){const [view,setView]=useState('graph');const [query,setQuery]=useState('');const [selected,setSelected]=useState<NodeData|null>(null);const [filter,setFilter]=useState<Category|'All'>('All');const [mobileNav,setMobileNav]=useState(false);const [listMode,setListMode]=useState(false);useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null);if(e.key==='/'&&!['INPUT','TEXTAREA'].includes((e.target as HTMLElement).tagName)){e.preventDefault();document.querySelector<HTMLInputElement>('.search input')?.focus()}};window.addEventListener('keydown',f);return()=>window.removeEventListener('keydown',f)},[]);return <div className="app"><Rail view={view} setView={setView}/>{mobileNav&&<div className="mobile-scrim" onClick={()=>setMobileNav(false)}/>}<div className="workspace"><Header query={query} setQuery={setQuery} onMenu={()=>setMobileNav(v=>!v)}/>{view==='graph'?<main className="graph-shell"><div className="graph-toolbar"><div><span className="eyebrow">SPATIAL MEMORY / 01</span><h1>Explore the mind.</h1></div><div className="filters">{(['All','Profile','Projects','Journal','System','Knowledge'] as const).map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}<button className="list-toggle" onClick={()=>setListMode(v=>!v)}>{listMode?'3D VIEW':'LIST VIEW'}</button></div></div>{listMode?<Fallback view="graph"/>:<div className="canvas-wrap"><GraphScene selected={selected} setSelected={setSelected} filter={filter} query={query}/></div>}<Legend/>{selected&&!listMode&&<Detail node={selected} onClose={()=>setSelected(null)} onAsk={()=>window.dispatchEvent(new CustomEvent('ask-node',{detail:selected.title}))}/>}<Chat selected={selected}/></main>:<Fallback view={view}/>}</div></div>}
function Fallback({view}:{view:string}){return <main className="fallback"><span className="eyebrow">{view.toUpperCase()} / ARIA HQ</span><h1>{view==='overview'?'Command center':view==='collections'?'Collections':view==='activity'?'Activity stream':'Settings'}</h1><p>This secondary surface stays intentionally quiet so the graph remains the primary workspace.</p><div className="fallback-list">{graph.nodes.map(n=><div key={n.id}><span className="node-dot" style={{background:COLORS[n.category]}}/><b>{n.title}</b><small>{n.category} · {n.connections} links</small></div>)}</div></main>}

createRoot(document.getElementById('root')!).render(<App/>);
